// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_data_impl
List generate_data_impl(int T, int N, NumericVector g, double sn, double b, double firerate, int framerate);
RcppExport SEXP _oasisBayeStat2025fall_generate_data_impl(SEXP TSEXP, SEXP NSEXP, SEXP gSEXP, SEXP snSEXP, SEXP bSEXP, SEXP firerateSEXP, SEXP framerateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type sn(snSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type firerate(firerateSEXP);
    Rcpp::traits::input_parameter< int >::type framerate(framerateSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_data_impl(T, N, g, sn, b, firerate, framerate));
    return rcpp_result_gen;
END_RCPP
}
// oasisAR1_cpp
List oasisAR1_cpp(NumericVector y, double g, double lam, double s_min);
RcppExport SEXP _oasisBayeStat2025fall_oasisAR1_cpp(SEXP ySEXP, SEXP gSEXP, SEXP lamSEXP, SEXP s_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    rcpp_result_gen = Rcpp::wrap(oasisAR1_cpp(y, g, lam, s_min));
    return rcpp_result_gen;
END_RCPP
}
// estimate_parameters_cpp
List estimate_parameters_cpp(NumericVector y);
RcppExport SEXP _oasisBayeStat2025fall_estimate_parameters_cpp(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_parameters_cpp(y));
    return rcpp_result_gen;
END_RCPP
}
// GetSn_cpp
double GetSn_cpp(arma::vec y, NumericVector range_ff, std::string method);
RcppExport SEXP _oasisBayeStat2025fall_GetSn_cpp(SEXP ySEXP, SEXP range_ffSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type range_ff(range_ffSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(GetSn_cpp(y, range_ff, method));
    return rcpp_result_gen;
END_RCPP
}
// estimate_g_corrected_cpp
double estimate_g_corrected_cpp(NumericVector y, double sn);
RcppExport SEXP _oasisBayeStat2025fall_estimate_g_corrected_cpp(SEXP ySEXP, SEXP snSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type sn(snSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_g_corrected_cpp(y, sn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_oasisBayeStat2025fall_generate_data_impl", (DL_FUNC) &_oasisBayeStat2025fall_generate_data_impl, 7},
    {"_oasisBayeStat2025fall_oasisAR1_cpp", (DL_FUNC) &_oasisBayeStat2025fall_oasisAR1_cpp, 4},
    {"_oasisBayeStat2025fall_estimate_parameters_cpp", (DL_FUNC) &_oasisBayeStat2025fall_estimate_parameters_cpp, 1},
    {"_oasisBayeStat2025fall_GetSn_cpp", (DL_FUNC) &_oasisBayeStat2025fall_GetSn_cpp, 3},
    {"_oasisBayeStat2025fall_estimate_g_corrected_cpp", (DL_FUNC) &_oasisBayeStat2025fall_estimate_g_corrected_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_oasisBayeStat2025fall(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
