# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' (Internal) C++ Implementation of Calcium Data Simulation
#'
#' This is the backend function that performs the heavy lifting for the 
#' simulation. It implements the AR process and Poisson spiking logic.
#'
#' @param T Integer. Total number of time frames.
#' @param N Integer. Number of neurons.
#' @param g Numeric vector. AR coefficients (length 1 for AR1, length 2 for AR2).
#' @param sn Double. Standard deviation of Gaussian noise.
#' @param b Double. Baseline fluorescence.
#' @param firerate Double. Target firing rate in Hz.
#' @param framerate Integer. Sampling rate in Hz.
#' 
#' @return A List containing three matrices:
#' \itemize{
#'   \item \code{Y}: Noisy fluorescence data (N x T).
#'   \item \code{c}: True calcium traces (N x T).
#'   \item \code{s}: Binary spike trains (N x T).
#' }
#' 
#' @section Note:
#' This function is not intended to be called directly by users. 
#' Please use the R wrapper function \code{generate_data()}.
#'
#' @noRd
generate_data_impl <- function(T, N, g, sn, b, firerate, framerate) {
    .Call(`_oasisBayeStat2025fall_generate_data_impl`, T, N, g, sn, b, firerate, framerate)
}

#' (Internal) Calculate Median of a Vector
#'
#' A helper function that computes the median of a vector using 
#' std::nth_element for efficient O(N) performance.
#'
#' @param v A std::vector<double> containing the data.
#' @return The median value as a double.
#' @section Warning:
#' This function modifies the input vector \code{v} in-place (partial sorting).
#' Do not use if the order of \code{v} must be preserved.
#' 
#' @noRd
NULL

#' (Internal) C++ Implementation of OASIS AR1 Deconvolution
#' 
#' This is the backend function that performs the heavy lifting for the 
#' deconvolution. It implements the Pool Adjacent Violators Algorithm (PAVA) 
#' for the AR(1) model logic.
#' 
#' @param y Numeric vector. The observed fluorescence trace.
#' @param g Double. The autoregressive decay factor (gamma). 
#'   Range: [0, 1). Closer to 1 implies slower decay.
#' @param lam Double. Sparsity penalty parameter (lambda). 
#'   Larger values result in fewer detected spikes (sparser solution).
#' @param s_min Double. Minimum spike size constraint.
#' 
#' @return A List containing two vectors:
#' \itemize{
#'   \item \code{c}: The inferred denoised calcium traces (same length as y).
#'   \item \code{s}: The inferred spike train (same length as y).
#' }
#' 
#' @section Note:
#' This function is not intended to be called directly by users. 
#' Please use the R wrapper function \code{oasis_ar1()}.
#' 
#' @keywords internal
oasisAR1_cpp <- function(y, g, lam, s_min) {
    .Call(`_oasisBayeStat2025fall_oasisAR1_cpp`, y, g, lam, s_min)
}

#' (Internal) C++ Implementation of Parameter Estimation
#' 
#' This is the backend function that estimates the noise standard deviation 
#' (sn) and the AR(1) decay constant (g) from the raw fluorescence data.
#' 
#' @param y Numeric vector. The observed fluorescence trace.
#' 
#' @details 
#' The noise standard deviation (\code{sn}) is estimated using the Median 
#' Absolute Deviation (MAD) of the first differences of the signal, 
#' which is robust to large spikes. This assumes the underlying noise is 
#' Gaussian and robustly scales the MAD factor (1.4826) accordingly.
#' 
#' The decay constant (\code{g}) is estimated using the Lag-1 Autocorrelation 
#' of the signal.
#' 
#' @return A List containing two named elements:
#' \itemize{
#'   \item \code{g}: The estimated autoregressive decay factor.
#'   \item \code{sn}: The estimated noise standard deviation.
#' }
#' 
#' @section Note:
#' This function is not intended to be called directly by users. 
#' Please use the R wrapper function \code{estimate_parameters()}.
#' 
#' @noRd
estimate_parameters_cpp <- function(y) {
    .Call(`_oasisBayeStat2025fall_estimate_parameters_cpp`, y)
}

#' (Internal) Estimate noise using PSD (C++ version)
#' 
#' @param y Input vector
#' @param range_ff Frequency range [low, high], e.g. c(0.25, 0.5)
#' @param method "mean" or "median"
#' 
#' @noRd
GetSn_cpp <- function(y, range_ff, method) {
    .Call(`_oasisBayeStat2025fall_GetSn_cpp`, y, range_ff, method)
}

#' (Internal) Estimate AR(1) Decay Factor with Noise Correction
#' 
#' @param y Numeric vector.
#' @param sn Double.
#' 
#' @noRd
estimate_g_corrected_cpp <- function(y, sn) {
    .Call(`_oasisBayeStat2025fall_estimate_g_corrected_cpp`, y, sn)
}

